services:
  frontend:
    build:
      context: ./smb-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Maps React's development server to localhost:3000
    volumes:
      - ./smb-frontend:/app # Mount the local frontend folder for live updates
      - /app/node_modules # Avoid overwriting container's node_modules
    depends_on:
      - backend
    networks:
      - app-network
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./smb-backend
      dockerfile: Dockerfile
    ports:
      - "3001:5000"
    volumes:
      - ./smb-backend:/app # Mount the local backend folder for live updates
      - /app/node_modules # Avoid overwriting container's node_modules
    depends_on:
      - db
    environment:
      - DB_USER=postgres
      - DB_PASS=saud
      - DB_NAME=smb-testing
      - DB_HOST=db # Use the container name as the host
      - DB_PORT=5432
      - LOG_LEVEL=info
      - NODE_ENV=development
      - SYNC=false
      - JWT_SECRET=HwMxbhtQoGApv1xZ8mapYEs1FYZhJjBSvq1S872sf0g
      - GOOGLE_CLIENT_ID=1066494215993-1ak960alqeb36ipal72v16mi54enve4e.apps.googleusercontent.com
      - PORT=5000
      - META_APP_ID=580223524518940
      - META_APP_SECRET=a7af85391305b32dcb1aca19036d7a8f
      - STRIPE_SECRET_KEY=sk_test_51QMqvzHqkh5hHCuXEr6mCk1a5cIsYAoCUY68gheZ7LxLSA40BZSrx37I68iooQ7PnrkVbe1xXaBqwI4dZZl5XUDK00JsbD7X79
      - FRONTEND_URL=http://localhost:3000
      - ENOM_BASE_URL=https://resellertest.enom.com
      - ENOM_UID=startmybusiness.com
      - ENOM_PWD=1998-2024EnomLLC.
    networks:
      - app-network
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432" # Maps PostgreSQL to localhost
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: saud
      POSTGRES_DB: smb-testing
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
