---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: engees11za-mongodb
  labels:
    owner: mongodb
    environment: prod
    app: 11za

spec:
  members: 3
  type: ReplicaSet
  version: "7.0.12"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: clusteradminuser
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: db-admin-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: readWriteAnyDatabase
          db: admin
        - name: dbAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: engees
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      template:
        spec:
          # resources can be specified by applying an override
          # per container name.
          containers:
            - name: mongod
              resources:
                limits:
                  cpu: 2
                  memory: 24Gi
                requests:
                  cpu: 2
                  memory: 12Gi
            - name: mongodb-agent
              resources:
                limits:
                  cpu: 500m
                  memory: 500Mi
                requests:
                  cpu: 200m
                  memory: 400Mi
          initContainers:
            - name: mongodb-agent-readinessprobe
              resources:
                limits:
                  cpu: 500m
                  memory: 200Mi
                requests:
                  cpu: 500m
                  memory: 200Mi
          nodeSelector:
            engees: mongodb
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: default
            resources:
              requests:
                storage: 200Gi
        - metadata:
            name: logs-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: default
            resources:
              requests:
                storage: 50Gi

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: db-admin-password
type: Opaque
stringData:
  password: 11zaWhatsAppEngeesCommunications6546
